#!/bin/bash

if [ -z $1 ]; then
  echo "No argument supplied"
  exit 1
fi

if [[ $1 != "xvid" && $1 != "x264" ]]; then
  echo "You must pass the codec as an argument to the script, e.g. either 'xvid' ot 'x264'"
  exit 128
fi

mkdir -p dest-$1

for FIL in `ls *.mp4 *.mov *.avi *.mkv *.webm | sort` ; do
  if [ $1 == "xvid" ]; then
    yes | avidemux3_cli --load "$FIL" --run settings/settings-$1.py --save dest-$1/${FIL%.*}.avi --quit
  elif [ $1 == "x264" ]; then
    yes | avidemux3_cli --load "$FIL" --run settings/settings-$1.py --save dest-$1/${FIL%.*}.mkv --quit
  fi
done
